# Generated by Django 5.2.12 on 2026-05-18 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0004_trainingtype_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='price_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Оплаченная сумма'),
        ),
        migrations.AddField(
            model_name='membership',
            name='promocode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gym.promocode', verbose_name='Промокод'),
        ),
        migrations.AddField(
            model_name='membershiptype',
            name='individual_session_price',
            field=models.DecimalField(decimal_places=2, default=30.0, max_digits=10, verbose_name='Цена индивидуального занятия'),
        ),
        migrations.AddField(
            model_name='training',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время окончания'),
        ),
        migrations.AddField(
            model_name='training',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='time',
            field=models.TimeField(verbose_name='Время начала'),
        ),
        migrations.CreateModel(
            name='PersonalTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('end_time', models.TimeField(verbose_name='Время окончания')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_trainings', to='gym.client', verbose_name='Клиент')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_trainings', to='gym.trainer', verbose_name='Инструктор')),
                ('training_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gym.trainingtype', verbose_name='Вид занятия')),
            ],
            options={
                'verbose_name': 'Индивидуальное занятие',
                'verbose_name_plural': 'Индивидуальные занятия',
                'ordering': ['-date', '-start_time'],
            },
        ),
    ]
