# Generated by Django 5.2.14 on 2026-09-12 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0005_membership_price_paid_membership_promocode_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('position', models.CharField(max_length=120, verbose_name='Должность')),
                ('duties', models.TextField(verbose_name='Выполняемые работы')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employee_photos/', verbose_name='Фото')),
                ('office', models.CharField(blank=True, max_length=50, verbose_name='Кабинет')),
                ('work_hours', models.CharField(default='Пн–Пт 09:00–18:00', max_length=100, verbose_name='Часы приёма')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок вывода')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['sort_order', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('description', models.CharField(max_length=255, verbose_name='Краткое описание')),
                ('category', models.CharField(choices=[('nutrition', 'Спортивное питание'), ('equipment', 'Экипировка и инвентарь'), ('medicine', 'Медицина и восстановление'), ('tech', 'Технологии и сервисы')], default='nutrition', max_length=20, verbose_name='Категория')),
                ('website', models.URLField(verbose_name='Сайт компании')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partner_logos/', verbose_name='Логотип')),
                ('since_year', models.PositiveIntegerField(verbose_name='Сотрудничаем с')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок вывода')),
            ],
            options={
                'verbose_name': 'Партнёр',
                'verbose_name_plural': 'Партнёры',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='slogan',
            field=models.CharField(blank=True, max_length=200, verbose_name='Слоган'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='video',
            field=models.FileField(blank=True, help_text='MP4-файл видеоэкскурсии по клубу', null=True, upload_to='company_videos/', verbose_name='Промо-видео'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='video_poster',
            field=models.ImageField(blank=True, null=True, upload_to='company_videos/', verbose_name='Постер видео'),
        ),
        migrations.AddField(
            model_name='membershiptype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='membership_images/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='membershiptype',
            name='short_description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Краткое описание для каталога'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Ключ сессии')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Наименование')),
                ('number', models.CharField(max_length=100, verbose_name='Регистрационный номер')),
                ('issued_by', models.CharField(max_length=255, verbose_name='Кем выдан')),
                ('issue_date', models.DateField(verbose_name='Дата выдачи')),
                ('valid_until', models.DateField(verbose_name='Действителен до')),
                ('description', models.TextField(blank=True, verbose_name='Содержание')),
                ('document', models.FileField(blank=True, null=True, upload_to='certificates/', verbose_name='Файл документа')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='gym.companyinfo', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='CompanyMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Год')),
                ('title', models.CharField(max_length=200, verbose_name='Событие')),
                ('description', models.TextField(verbose_name='Описание')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='gym.companyinfo', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Событие истории',
                'verbose_name_plural': 'История компании',
                'ordering': ['year'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True, verbose_name='Номер заказа')),
                ('full_name', models.CharField(max_length=150, verbose_name='ФИО плательщика')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('payment_method', models.CharField(choices=[('card', 'Банковская карта'), ('erip', 'ЕРИП «Расчёт»'), ('cash', 'Наличными на ресепшене')], default='card', max_length=10, verbose_name='Способ оплаты')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма без скидки')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Скидка')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Итого к оплате')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('new', 'Ожидает оплаты'), ('paid', 'Оплачен'), ('cancelled', 'Отменён')], default='new', max_length=10, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата оформления')),
                ('promocode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gym.promocode', verbose_name='Промокод')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Наименование')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за единицу')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='Количество')),
                ('membership_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gym.membershiptype', verbose_name='Абонемент')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='gym.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Позиция заказа',
                'verbose_name_plural': 'Позиции заказа',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='Количество')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='gym.cart', verbose_name='Корзина')),
                ('membership_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.membershiptype', verbose_name='Абонемент')),
            ],
            options={
                'verbose_name': 'Позиция корзины',
                'verbose_name_plural': 'Позиции корзины',
                'ordering': ['added_at'],
                'unique_together': {('cart', 'membership_type')},
            },
        ),
    ]
